バリデーションをぽちぽちと設定していく
kufu/kirico pull request #3
Opened 2017-02-01 10:56 UTC by kakipo

2017-02-01 11:29 UTC, kakipo commented
```ruby
[16] pry(main)> [:eccyan, :mserizawa, :elbowroomer, :atsushim, :purintai].sample(2)
=> [:atsushim, :eccyan]
```

2017-02-01 11:29 UTC, kakipo commented
@AtsushiM @eccyan お手すきでレビューをお願いします〜 :pray:

2017-02-02 07:03 UTC, AtsushiM commented on lib/kirico/validators/sjis_bytesize_validator.rb
> +      value_length = value.to_s.encode('Shift_JIS').bytesize
👀 
nilの場合がありえるのでto_sで回避してる

2017-02-02 07:10 UTC, AtsushiM commented on lib/kirico/models/changing_address_record.rb
> +    validates :new_address, charset: { accept: [:all] }, sjis_bytesize: { in: 0..74 }, allow_blank: true
👀 
資料上は0~37が文字数の範囲だけどここは種別：漢字だからx2の値になっている。

2017-02-02 07:15 UTC, AtsushiM commented on lib/kirico/models/changing_address_record.rb
> +    validates :memo, charset: { accept: [:all] }, sjis_bytesize: { in: 0..75 }, allow_blank: true
資料が見にくい...
<img width="661" alt="2017-02-02 16 11 47" src="https://cloud.githubusercontent.com/assets/773467/22540228/52473ce6-e962-11e6-8a2c-33c7ca32ec72.png">

種別:漢字の場合、そもそも数字・英字・カナの文字を含むためこれで問題ない

2017-02-02 07:20 UTC, kakipo commented on lib/kirico/models/changing_address_record.rb
> +    validates :new_address, charset: { accept: [:all] }, sjis_bytesize: { in: 0..74 }, allow_blank: true
（FYI）
資料のミス、、、だとは思うのですが、種別「漢字」のみの項目でも実際は半角英数字使えました。
ので実際の挙動に合わせて `:all` としています。

2017-02-02 07:23 UTC, AtsushiM approved these changes
LGTMです！

2017-02-02 07:36 UTC, AtsushiM commented on lib/kirico/models/changing_address_record.rb
> +    validates :new_address, charset: { accept: [:all] }, sjis_bytesize: { in: 0..74 }, allow_blank: true
> 実際の挙動に合わせて :all としています。

なるほど。。。
了解です！

2017-02-06 04:16 UTC, eccyan requested changes
確認方法で確認しようとすると undefined method が発生します。

```pry
> rec = FactoryGirl.build(:changing_address_record)
=> #<Kirico::ChangingAddressRecord:0x007fbc9bd8a8d8
 ...
[16] pry(main)> rec.valid?
NoMethodError: undefined method `valid?' for #<Kirico::ChangingAddressRecord:0x007fbc9bd8a8d8>
from (pry):15:in `__pry__'
```

ご確認、お願い致します。

2017-02-06 04:23 UTC, eccyan commented on lib/kirico/models/changing_address_record.rb
> +    validates :new_address, charset: { accept: [:all] }, sjis_bytesize: { in: 0..74 }, allow_blank: true
> 資料のミス、、、だとは思うのですが、種別「漢字」のみの項目でも実際は半角英数字使えました。

ドキュメンテーションの更新か…

2017-02-07 03:48 UTC, kakipo commented
@eccyan アレ・・・。すいません 💦 

kirico 直下で `bundle list` 打つとどうなりますでしょうか？

2017-02-08 11:55 UTC, eccyan commented
@kakipo 遅くなって申し訳ない 🙇 こちら結果ですー

```
Gems included by the bundle:
  * activemodel (5.0.1)
  * activesupport (5.0.1)
  * ast (2.3.0)
  * axiom-types (0.1.1)
  * bundler (1.14.3)
  * byebug (9.0.6)
  * coderay (1.1.1)
  * coercible (1.0.0)
  * concurrent-ruby (1.0.4)
  * descendants_tracker (0.0.4)
  * diff-lcs (1.3)
  * equalizer (0.0.11)
  * era_ja (0.5.0)
  * factory_girl (4.8.0)
  * ffi (1.9.17)
  * formatador (0.2.5)
  * guard (2.14.0)
  * guard-bundler (2.1.0)
  * guard-compat (1.2.1)
  * guard-rspec (4.7.3)
  * guard-rubocop (1.2.0)
  * i18n (0.7.0)
  * ice_nine (0.11.2)
  * kirico (0.1.0)
  * listen (3.1.5)
  * lumberjack (1.0.11)
  * method_source (0.8.2)
  * minitest (5.10.1)
  * nenv (0.3.0)
  * notiffany (0.1.1)
  * parser (2.3.3.1)
  * powerpack (0.1.1)
  * pry (0.10.4)
  * pry-byebug (3.4.2)
  * rainbow (2.2.1)
  * rake (10.4.2)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.7)
  * rspec (3.5.0)
  * rspec-core (3.5.4)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * rubocop (0.47.1)
  * ruby-progressbar (1.8.1)
  * ruby_dep (1.5.0)
  * shellany (0.0.1)
  * slop (3.6.0)
  * thor (0.19.4)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
  * unicode-display_width (1.1.3)
  * virtus (1.0.5)

```

2017-02-09 00:22 UTC, kakipo commented
@eccyan 確認ありがとうございます 🙏 

殆ど差分ないのになんでだろう... 💦 

![image](https://cloud.githubusercontent.com/assets/2214179/22763580/2e84c692-eea9-11e6-85d5-5b4e0ed735a3.png)

ちょっと他の人の環境でも見てみます...！

2017-02-09 00:26 UTC, eccyan commented
そもそも、`valid?`が定義されてないってなんでだろ…

2017-02-09 00:28 UTC, kakipo commented
@eccyan 

```
include ActiveModel::Validations
```

が実行されてない感じしますね...

もしかして: ブランチが違う

2017-02-09 00:29 UTC, eccyan commented
ふぁ！？

2017-02-09 00:51 UTC, eccyan approved these changes
@kakipo ブランチ切り替えてなかったごめんんさい 🙏 
動作は問題ありません！LGTMでっす！

![](https://media4.giphy.com/media/cZ7rmKfFYOvYI/200.gif#8)

2017-02-09 01:26 UTC, kakipo commented
@eccyan あざす！ :pray:

2017-02-09 01:26 UTC, merged